Window_With_Name(): make sure cookies.get_net_wm_name is set
Reported by Oracle Parfait:

Error: Uninitialised memory
   Uninitialised memory [uninitialised-mem] (CWE 456):
      Possible access to uninitialised memory referenced by 'cookies'
        at line 289 of dsimple.c in function 'recursive_Window_With_Name'.
        called at line 420 in function 'Window_With_Name' with cookies = &cookies.
        Path avoiding write at line 416
        Write does not overlap at line 417
        Write does not overlap at line 418
          cookies allocated at line 410
          cookies passed in at line 276 in function 'recursive_Window_With_Name'

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>